site_name: Auth-reg test
copyright: "&copy; Cyber Science Infrastructure Development Department, National Institute of Informatics"

repo_url: https://github.com/letticia/auth-reg
repo_name: auth-reg

theme:
  name: material
  palette:
    primary: red
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
  - Introduction: index.md

extra:
  generator: false
  alternate:
    - name: English
      link: /en/
      lang: en 
    - name: Japanese
      link: /
      lang: ja 

