site_name: Auth-reg test
copyright: "&copy; Cyber Science Infrastructure Development Department, National Institute of Informatics"

repo_url: https://github.com/letticia/auth-reg
repo_name: auth-reg

theme:
  name: material
  palette:
    primary: red
  features:
#    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate

nav:
  - トップページ: index.md
  - コンテンツ1: 
    - コンテンツ1-1: contents_1_1.md
    - コンテンツ1-2: contents_1_2.md
  - コンテンツ2: contents_2.md

extra:
  homepage: https://letticia.github.io/auth-reg/
  generator: false
  alternate:
    - name: English
      link: /auth-reg/en/
      lang: en 
    - name: Japanese
      link: /auth-reg/
      lang: ja 

